# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaSistemaReconhecimentoFacial.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from funcoesSystem import abrir_imgs as img

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 456)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.img_padrao = QtWidgets.QLabel(self.centralwidget)
        self.img_padrao.setGeometry(QtCore.QRect(10, 60, 291, 301))
        self.img_padrao.setStyleSheet("image: url(:/semImg/semImagem.png)")
        self.img_padrao.setText("")
        self.img_padrao.setObjectName("img_padrao")
        self.img_teste = QtWidgets.QLabel(self.centralwidget)
        self.img_teste.setGeometry(QtCore.QRect(360, 70, 291, 281))
        self.img_teste.setStyleSheet("image: url(:/semImg/semImagem.png)")
        self.img_teste.setText("")
        self.img_teste.setObjectName("img_teste")
        self.escrita = QtWidgets.QLabel(self.centralwidget)
        self.escrita.setEnabled(True)
        self.escrita.setGeometry(QtCore.QRect(130, 0, 391, 31))
        self.escrita.setStyleSheet("COLLOR rgb(0, 255, 255)")
        self.escrita.setObjectName("escrita")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 20, 621, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(320, 40, 20, 321))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.bt_img_padrao = QtWidgets.QPushButton(self.centralwidget)
        self.bt_img_padrao.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.bt_img_padrao.setObjectName("bt_img_padrao")
        self.escrita_img_padrao = QtWidgets.QLabel(self.centralwidget)
        self.escrita_img_padrao.setGeometry(QtCore.QRect(90, 50, 121, 21))
        self.escrita_img_padrao.setObjectName("escrita_img_padrao")
        self.escrita_img_teste = QtWidgets.QLabel(self.centralwidget)
        self.escrita_img_teste.setGeometry(QtCore.QRect(440, 50, 101, 21))
        self.escrita_img_teste.setObjectName("escrita_img_teste")
        self.bt_img_teste = QtWidgets.QPushButton(self.centralwidget)
        self.bt_img_teste.setGeometry(QtCore.QRect(360, 50, 75, 23))
        self.bt_img_teste.setObjectName("bt_img_teste")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 360, 621, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.bt_verificar = QtWidgets.QPushButton(self.centralwidget)
        self.bt_verificar.setGeometry(QtCore.QRect(540, 390, 75, 23))
        self.bt_verificar.setObjectName("bt_verificar")
        self.txt_output = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_output.setEnabled(False)
        self.txt_output.setGeometry(QtCore.QRect(140, 390, 391, 20))
        self.txt_output.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_output.setObjectName("txt_output")
        self.escrita_result = QtWidgets.QLabel(self.centralwidget)
        self.escrita_result.setGeometry(QtCore.QRect(40, 380, 91, 31))
        self.escrita_result.setObjectName("escrita_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.escrita.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">SISTEMA DE RECONHECIMENTO FACIAL</span></p></body></html>"))
        self.bt_img_padrao.setText(_translate("MainWindow", "Carregar"))
        self.escrita_img_padrao.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">imagem padrão</span></p></body></html>"))
        self.escrita_img_teste.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">imagem teste</span></p></body></html>"))
        self.bt_img_teste.setText(_translate("MainWindow", "Carregar"))
        self.bt_verificar.setText(_translate("MainWindow", "Verificar"))
        self.escrita_result.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Resultado </span></p></body></html>"))


        ### BOTOES DO SISTEMA ###
        self.bt_img_padrao.clicked.connect(self.imagem_fixa)
        self.bt_img_teste.clicked.connect(self.imagem_para_teste)


    ### funções do sistema ###
    def imagem_fixa(self):
        self.imagem = img.localizar_arquivo()
        if len(self.imagem) > 0:
            self.img_padrao.setStyleSheet(f"image: url({self.imagem})")


    def imagem_para_teste(self):
        self.imagem = img.localizar_arquivo()
        if len(self.imagem) > 0:
            self.img_teste.setStyleSheet(f"image: url({self.imagem})")

from Imagens import semImg

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
